## Create VSCode Extension Directory
## Downloads VSCode extensions from local web server during ISO build
## NOTE: This file is auto-generated by Setup/Scripts/update_vscode_kickstart.sh
##       Run Setup/Scripts/download_vscode_extensions.sh to update extensions

mkdir -p /opt/FedoraRemix/VSCode
cd /opt/FedoraRemix/VSCode

wget http://localhost/VSCode/aaron-bond.better-comments-3.0.2.vsix
wget http://localhost/VSCode/adpyke.codesnap-1.3.4.vsix
wget http://localhost/VSCode/asciidoctor.asciidoctor-vscode-3.4.5.vsix
wget http://localhost/VSCode/ChrisChinchilla.vale-vscode-0.32.0.vsix
wget http://localhost/VSCode/Codeium.codeium-1.49.2.vsix
wget http://localhost/VSCode/eamodio.gitlens-2025.12.604.vsix
wget http://localhost/VSCode/esbenp.prettier-vscode-11.0.2.vsix
wget http://localhost/VSCode/flobilosaurus.vscode-asciidoc-slides-1.3.0.vsix
wget http://localhost/VSCode/Gruntfuggly.todo-tree-0.0.226.vsix
wget http://localhost/VSCode/ms-python.python-2025.19.2025120401.vsix
wget http://localhost/VSCode/MS-vsliveshare.vsliveshare-1.0.5959.vsix
wget http://localhost/VSCode/peterjonsson.kickstart-language-support-0.0.14.vsix
wget http://localhost/VSCode/pnp.polacode-0.3.4.vsix
wget http://localhost/VSCode/redhat.ansible-25.12.1.vsix
wget http://localhost/VSCode/redhat.vscode-xml-0.29.2025112508.vsix
wget http://localhost/VSCode/redhat.vscode-yaml-1.20.2025120408.vsix
