#!/bin/bash
#
# Update VSCode Kickstart Snippet
# Regenerates the setup-vscode-extensions.ks file based on actual files in Setup/files/VSCode/
#
# Usage: ./update_vscode_kickstart.sh
#

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Paths
VSCODE_DIR="${SCRIPT_DIR}/../files/VSCode"
KICKSTART_FILE="${SCRIPT_DIR}/../Kickstarts/KickstartSnippets/setup-vscode-extensions.ks"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo "=========================================="
echo "  Update VSCode Kickstart Snippet"
echo "=========================================="
echo ""

# Check if VSCode directory exists
if [[ ! -d "$VSCODE_DIR" ]]; then
    echo "Error: VSCode directory not found: $VSCODE_DIR"
    exit 1
fi

# Get list of .vsix files
vsix_files=()
for f in "$VSCODE_DIR"/*.vsix; do
    [[ -e "$f" ]] && vsix_files+=("$(basename "$f")")
done
# Sort the array
IFS=$'\n' vsix_files=($(sort <<<"${vsix_files[*]}")); unset IFS

if [[ ${#vsix_files[@]} -eq 0 ]]; then
    echo "Error: No .vsix files found in $VSCODE_DIR"
    exit 1
fi

echo -e "${BLUE}[INFO]${NC} Found ${#vsix_files[@]} extensions in $VSCODE_DIR"
echo ""

# Generate the kickstart file
cat > "$KICKSTART_FILE" << 'HEADER'
## Create VSCode Extension Directory
## Downloads VSCode extensions from local web server during ISO build
## NOTE: This file is auto-generated by Setup/Scripts/update_vscode_kickstart.sh
##       Run Setup/Scripts/download_vscode_extensions.sh to update extensions

mkdir -p /opt/FedoraRemix/VSCode
cd /opt/FedoraRemix/VSCode

HEADER

# Add wget commands for each extension
for vsix in "${vsix_files[@]}"; do
    echo "wget -q http://localhost/VSCode/${vsix}" >> "$KICKSTART_FILE"
done

echo -e "${GREEN}[SUCCESS]${NC} Updated: $KICKSTART_FILE"
echo ""
echo "Extensions included:"
for vsix in "${vsix_files[@]}"; do
    echo "  - ${vsix}"
done
echo ""

